### ISSUE TITLE
ZXHN F450获取的文件无法解码

### ISSUE THREAD

**Issue by BiliRumble** [wx1183618058/ZET-Optical-Network-Terminal-Decoder#9]
PS F:\zttools> .\ztecfg.exe -d AESCBC -i .\db_user_cfg.xml -o sb.cfg
作者：欲断魂
介绍：仅支持中兴光猫3.0配置加解密
cfgFileDecryAESCBC magic=0x4030201 sign=0x0
Traceback (most recent call last):
  File "ztecfg.py", line 138, in <module>
  File "ztecfg.py", line 94, in cfgFileDecryAESCBC
  File "Crypto\Cipher\_mode_cbc.py", line 246, in decrypt
ValueError: Data must be padded to 16 byte boundary in CBC mode
[16120] Failed to execute script ztecfg

**Comment by Z2FvanVu** [comment]
我用AESCBC解密也遇到了同样的错误，后面用CRC解密成功了，指令`.\ztecfg.exe -d CRC -i .\db_user_cfg.xml -o db_user_cfg_decode.cfg`。附上解密成功的光猫型号以供参考。

> 设备型号 | ZXHN F450
设备标识号 | *
硬件版本号 | V2.0
软件版本号 | V2.0.0P1T1

> D:\cfg>.\ztecfg.exe -d AESCBC -i .\db_user_cfg.xml -o sb.cfg
作者：欲断魂
介绍：仅支持中兴光猫3.0配置加解密
cfgFileDecryAESCBC magic=0x4030201 sign=0x0
Traceback (most recent call last):
  File "ztecfg.py", line 138, in <module>
  File "ztecfg.py", line 94, in cfgFileDecryAESCBC
  File "Crypto\Cipher\_mode_cbc.py", line 246, in decrypt
ValueError: Data must be padded to 16 byte boundary in CBC mode
[12452] Failed to execute script ztecfg

> D:\cfg>.\ztecfg.exe -d CRC -i .\db_user_cfg.xml -o db_user_cfg_decode.cfg
> 作者：欲断魂
> 介绍：仅支持中兴光猫3.0配置加解密
> cfgFileDecryCRC magic=0x1020304 size=0x5f7ac comp_size=0x7c42

**Comment by BiliRumble** [comment]
谢谢，已解决

**Comment by BiliRumble** [comment]
（；´д｀）ゞ卧槽我怎么解决的来着
